[package]
name = "OxyX1/oxyumai"
version = "0.0.1"
description = "A website built for finetuning and building ais"
license-file = "./LICENSE.md" # OR license-file = "./LICENSE.md"
readme = "./README.md"
repository = "https://github.com/OxyX1/oxyumai.git"
homepage = "https://oxyumai.wasmer.io"
entrypoint = "oxyumai"
 
# ...